import React, { useState, useEffect } from 'react';
import toast from 'react-hot-toast';
import { Save, FileJson, Check, MessageSquare, List } from 'lucide-react';

export const GptTrainingStudio = () => {
  const categories = [
    "Global (All Categories)",
    "Random (Any Issue)",
    "Booking",
    "Cancellation",
    "Reschedule",
    "Refund",
    "Baggage",
    "Check-in",
    "Meal / Seat",
    "Visa / Travel Advisory",
    "Other"
  ];
  
  const [promptData, setPromptData] = useState({});
  const [selectedCategory, setSelectedCategory] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isSaved, setIsSaved] = useState(false);
  const [loading, setLoading] = useState(true);

  const fetchPromptContext = async () => {
    try {
      setLoading(true);
      const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:3000/api';
      const res = await fetch(`${apiUrl}/v1/prompt`);
      if (!res.ok) throw new Error('Failed to fetch prompt context');
      const data = await res.json();
      
      // Migrate from old global example if needed
      if (data._GlobalExample) {
        data["Global (All Categories)"] = data["Global (All Categories)"] || {};
        data["Global (All Categories)"].perfectExample = data._GlobalExample;
        delete data._GlobalExample;
      }
      
      setPromptData(data || {});
    } catch (err) {
      toast.error('Failed to load GPT examples');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchPromptContext();
  }, []);

  const handleSave = async () => {
    try {
      setIsSubmitting(true);
      const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:3000/api';
      const res = await fetch(`${apiUrl}/v1/prompt`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(promptData)
      });

      if (!res.ok) throw new Error('Failed to save GPT example');

      toast.success('GPT Example updated successfully!');
      setIsSaved(true);
      setTimeout(() => {
        setIsSaved(false);
        setSelectedCategory(""); // Clear the editor
      }, 1500);
    } catch (err) {
      toast.error(err.message);
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleDelete = async (categoryToDelete) => {
    if (!window.confirm(`Are you sure you want to delete the GPT example for "${categoryToDelete}"?`)) return;

    try {
      const updatedData = { ...promptData };
      if (updatedData[categoryToDelete]) {
        delete updatedData[categoryToDelete].perfectExample;
        // If category is completely empty now, we could delete it, but let's just delete the perfectExample key
        if (!updatedData[categoryToDelete].globalInstructions) {
          delete updatedData[categoryToDelete];
        }
      }
      setPromptData(updatedData);

      const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:3000/api';
      const res = await fetch(`${apiUrl}/v1/prompt`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(updatedData)
      });

      if (!res.ok) throw new Error('Failed to delete example');
      toast.success(`${categoryToDelete} GPT example deleted successfully!`);
    } catch (err) {
      toast.error(err.message);
    }
  };

  const handleEdit = (category) => {
    setSelectedCategory(category);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  if (loading) {
    return <div className="text-gray-400 p-8 text-center animate-pulse">Loading GPT Training Studio...</div>;
  }

  const currentExample = promptData[selectedCategory]?.perfectExample || '';
  const activeCategories = Object.entries(promptData).filter(([_, data]) => data?.perfectExample?.trim());

  const handleExampleChange = (e) => {
    setPromptData(prev => ({
      ...prev,
      [selectedCategory]: {
        ...(prev[selectedCategory] || {}),
        perfectExample: e.target.value
      }
    }));
  };

  return (
    <div className="space-y-8 animate-in fade-in duration-200">
      <div className="bg-[#111827] border border-[#1F2937] rounded-2xl overflow-hidden shadow-xl flex flex-col" style={{ height: 'calc(100vh - 120px)', minHeight: '600px' }}>
        <div className="shrink-0 px-8 py-6 border-b border-[#1F2937] bg-gradient-to-r from-purple-900/20 to-pink-900/10 z-10">
          <h2 className="text-2xl font-bold text-white mb-2 flex items-center gap-3">
            <MessageSquare className="w-7 h-7 text-purple-400" />
            GPT Training Examples
          </h2>
          <p className="text-sm text-gray-300 max-w-3xl leading-relaxed">
            Paste a perfect QA report generated by ChatGPT or another AI here for a specific category. The local AI will mimic its exact structure and strictness when analyzing chats in this category.
          </p>
        </div>

        <div className="flex-1 overflow-y-auto p-8 space-y-8">
          
          {/* Category Selector */}
          <div className="bg-[#0B1020] border border-[#1F2937] p-6 rounded-xl shadow-inner mb-8 flex items-center justify-between shrink-0">
            <div>
              <h3 className="text-sm font-bold text-gray-300 uppercase tracking-wider mb-1">Issue Category</h3>
              <p className="text-xs text-gray-500">Select the category to define its specific perfect output example.</p>
            </div>
            <select
              value={selectedCategory}
              onChange={(e) => setSelectedCategory(e.target.value)}
              className="w-72 bg-[#111827] border border-[#374151] text-white text-sm rounded-xl px-4 py-3 focus:outline-none focus:border-purple-500 transition-colors cursor-pointer font-bold"
            >
              <option value="" disabled>Select Category...</option>
              {categories.map(c => (
                <option key={c} value={c}>{c}</option>
              ))}
            </select>
          </div>

          <div className="space-y-4 flex flex-col h-full">
            <div className="flex items-start justify-between shrink-0">
              <div>
                <h3 className="text-lg font-bold text-white flex items-center gap-2">
                  <FileJson className="w-5 h-5 text-emerald-400" />
                  Perfect Category Example
                </h3>
                <p className="text-xs text-gray-400 mt-1">
                  Format: JSON or Plain Text. <span className="text-purple-400 font-medium">This will act as the absolute ground truth for output format for this category.</span>
                </p>
              </div>
            </div>
            <div className="relative group flex-1">
              <textarea 
                value={currentExample}
                onChange={handleExampleChange}
                disabled={!selectedCategory}
                placeholder={selectedCategory ? '{\n  "qaScore": 85,\n  "status": "Warning",\n  "errorType": "Misleading",\n  "findings": [...]\n}' : "Select a category above to start typing..."}
                className="w-full min-h-[300px] h-full bg-[#0B1020] border border-[#1F2937] text-gray-200 text-sm rounded-xl p-5 focus:outline-none focus:border-purple-500/50 focus:ring-1 focus:ring-purple-500/50 transition-all resize-none shadow-inner font-mono disabled:opacity-50 disabled:cursor-not-allowed"
                spellCheck="false"
              />
            </div>
          </div>
        </div>

        <div className="shrink-0 px-8 py-6 border-t border-[#1F2937] bg-[#111827] flex justify-end z-10">
          <button 
            onClick={handleSave}
            disabled={isSubmitting || isSaved}
            className={`flex items-center gap-2 px-8 py-3 disabled:opacity-80 font-bold rounded-xl transition-all shadow-md transform hover:-translate-y-0.5 active:translate-y-0 ${
              isSaved 
                ? 'bg-emerald-600 hover:bg-emerald-500 text-white shadow-emerald-500/20' 
                : 'bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-500 hover:to-pink-500 text-white shadow-purple-500/30'
            }`}
          >
            {isSubmitting ? (
              'Saving GPT Example...'
            ) : isSaved ? (
              <>
                <Check className="w-5 h-5" />
                Saved Successfully!
              </>
            ) : (
              <>
                <Save className="w-5 h-5" />
                Save Category Example
              </>
            )}
          </button>
        </div>
      </div>

      {/* Active Contexts List */}
      <div className="bg-[#111827] border border-[#1F2937] rounded-2xl overflow-hidden mt-8 shadow-xl">
        <div className="px-6 py-4 border-b border-[#1F2937] flex items-center justify-between">
          <h3 className="text-base font-bold text-white flex items-center gap-2">
            <List className="w-5 h-5 text-purple-400" />
            Active Category Examples ({activeCategories.length})
          </h3>
        </div>
        
        <div className="overflow-x-auto">
          <table className="w-full text-sm text-left">
            <thead className="text-xs text-gray-400 uppercase bg-[#0B1020] border-b border-[#1F2937]">
              <tr>
                <th className="px-6 py-4 font-bold tracking-wider">Category</th>
                <th className="px-6 py-4 font-bold tracking-wider">Example Preview</th>
                <th className="px-6 py-4 font-bold tracking-wider text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#1F2937]">
              {activeCategories.map(([category, data]) => (
                <tr key={category} className="hover:bg-[#0B1020]/50 transition-colors">
                  <td className="px-6 py-4 font-medium text-white whitespace-nowrap">
                    {category}
                  </td>
                  <td className="px-6 py-4 text-gray-400 max-w-2xl truncate">
                    {data.perfectExample}
                  </td>
                  <td className="px-6 py-4 text-right space-x-3 whitespace-nowrap">
                    <button 
                      onClick={() => handleEdit(category)}
                      className="text-purple-400 hover:text-purple-300 font-medium text-xs uppercase"
                    >
                      Edit
                    </button>
                    <button 
                      onClick={() => handleDelete(category)}
                      className="text-red-400 hover:text-red-300 font-medium text-xs uppercase"
                    >
                      Delete
                    </button>
                  </td>
                </tr>
              ))}
              {activeCategories.length === 0 && (
                <tr>
                  <td colSpan="3" className="px-6 py-8 text-center text-gray-500">
                    No active category examples found. Select a category above and save to create one.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
